apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: my-topic
  labels:
    strimzi.io/cluster: my-cluster
spec:
  replicas: 3
  partitions: 12
--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: java-http-vertx-consumer
  name: java-http-vertx-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-http-vertx-consumer
  template:
    metadata:
      labels:
        app: java-http-vertx-consumer
    spec:
      containers:
      - name: java-http-vertx-consumer
        image: quay.io/strimzi-examples/java-http-vertx-consumer:latest
        env:
          - name: HOSTNAME
            value: my-bridge-bridge-service
          - name: PORT
            value: "8080"
          - name: TOPIC
            value: my-topic
          - name: CLIENTID
            value: "my-consumer"
          - name: GROUPID
            value: "my-group"
          - name: POLL_INTERVAL
            value: "1000"
---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: java-http-vertx-producer
  name: java-http-vertx-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-http-vertx-producer
  template:
    metadata:
      labels:
        app: java-http-vertx-producer
    spec:
      containers:
      - name: java-http-vertx-producer
        image: quay.io/strimzi-examples/java-http-vertx-producer:latest
        env:
          - name: HOSTNAME
            value: my-bridge-bridge-service
          - name: PORT
            value: "8080"
          - name: TOPIC
            value: my-topic
          - name: SEND_INTERVAL
            value: "1000"
